import OpenAI from 'openai';
import { logger } from '../utils/logger';

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

interface UserProfile {
  age: number;
  gender: string;
  height: number; // cm
  weight: number; // kg
  activityLevel: string;
  goals: string[];
  allergies: string[];
  dietType: string;
  tdee: number; // Total Daily Energy Expenditure
}

interface MealPlanRequest {
  userProfile: UserProfile;
  duration: 'daily' | 'weekly';
  preferences?: {
    cuisine?: string[];
    cookingTime?: 'quick' | 'moderate' | 'extensive';
    mealCount?: number;
  };
}

interface GeneratedMeal {
  name: string;
  mealType: 'BREAKFAST' | 'LUNCH' | 'DINNER' | 'SNACK' | 'PRE_WORKOUT' | 'POST_WORKOUT';
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber?: number;
  sugar?: number;
  sodium?: number;
  ingredients: Array<{
    name: string;
    amount: string;
    unit: string;
  }>;
  instructions: string[];
  prepTime: number; // minutes
  cookTime: number; // minutes
  servings: number;
  difficulty: 'BEGINNER' | 'INTERMEDIATE' | 'ADVANCED';
  tags: string[];
}

interface GeneratedMealPlan {
  title: string;
  description: string;
  totalCalories: number;
  totalProtein: number;
  totalCarbs: number;
  totalFat: number;
  totalFiber: number;
  totalSugar: number;
  meals: GeneratedMeal[];
  groceryList: Array<{
    category: string;
    items: Array<{
      name: string;
      amount: string;
      unit: string;
    }>;
  }>;
}

export class AIService {
  static async generateMealPlan(request: MealPlanRequest): Promise<GeneratedMealPlan> {
    try {
      const { userProfile, duration, preferences = {} } = request;
      
      const prompt = this.buildMealPlanPrompt(userProfile, duration, preferences);
      
      const response = await openai.chat.completions.create({
        model: 'gpt-4',
        messages: [
          {
            role: 'system',
            content: 'You are a professional nutritionist and chef. Generate detailed, personalized meal plans with exact nutritional information, ingredients, and cooking instructions. Always respond with valid JSON.'
          },
          {
            role: 'user',
            content: prompt
          }
        ],
        temperature: 0.7,
        max_tokens: 4000
      });

      const content = response.choices[0]?.message?.content;
      if (!content) {
        throw new Error('No content generated by AI');
      }

      // Parse and validate the JSON response
      const mealPlan = JSON.parse(content);
      return this.validateAndFormatMealPlan(mealPlan);
    } catch (error) {
      logger.error('AI meal plan generation failed:', error);
      throw new Error('Failed to generate meal plan');
    }
  }

  static async generateWorkoutRecommendations(
    userProfile: UserProfile,
    availableWorkouts: any[],
    preferences?: {
      duration?: number; // minutes
      equipment?: string[];
      muscleGroups?: string[];
      difficulty?: string;
    }
  ) {
    try {
      const prompt = this.buildWorkoutRecommendationPrompt(userProfile, availableWorkouts, preferences);
      
      const response = await openai.chat.completions.create({
        model: 'gpt-4',
        messages: [
          {
            role: 'system',
            content: 'You are a professional personal trainer. Recommend workout routines based on user goals, fitness level, and available equipment. Always respond with valid JSON.'
          },
          {
            role: 'user',
            content: prompt
          }
        ],
        temperature: 0.6,
        max_tokens: 2000
      });

      const content = response.choices[0]?.message?.content;
      if (!content) {
        throw new Error('No content generated by AI');
      }

      return JSON.parse(content);
    } catch (error) {
      logger.error('AI workout recommendation failed:', error);
      throw new Error('Failed to generate workout recommendations');
    }
  }

  static async swapMeal(
    currentMeal: GeneratedMeal,
    userProfile: UserProfile,
    mealType: string,
    preferences?: {
      cuisine?: string[];
      cookingTime?: string;
      avoidIngredients?: string[];
    }
  ): Promise<GeneratedMeal> {
    try {
      const prompt = this.buildMealSwapPrompt(currentMeal, userProfile, mealType, preferences);
      
      const response = await openai.chat.completions.create({
        model: 'gpt-4',
        messages: [
          {
            role: 'system',
            content: 'You are a professional nutritionist and chef. Generate a replacement meal that matches the nutritional profile and dietary requirements of the original meal. Always respond with valid JSON.'
          },
          {
            role: 'user',
            content: prompt
          }
        ],
        temperature: 0.7,
        max_tokens: 1500
      });

      const content = response.choices[0]?.message?.content;
      if (!content) {
        throw new Error('No content generated by AI');
      }

      const newMeal = JSON.parse(content);
      return this.validateAndFormatMeal(newMeal);
    } catch (error) {
      logger.error('AI meal swap failed:', error);
      throw new Error('Failed to generate meal replacement');
    }
  }

  private static buildMealPlanPrompt(userProfile: UserProfile, duration: string, preferences: any): string {
    return `
Generate a ${duration} meal plan for the following user profile:

**User Profile:**
- Age: ${userProfile.age} years
- Gender: ${userProfile.gender}
- Height: ${userProfile.height} cm
- Weight: ${userProfile.weight} kg
- Activity Level: ${userProfile.activityLevel}
- Goals: ${userProfile.goals.join(', ')}
- Allergies: ${userProfile.allergies.length > 0 ? userProfile.allergies.join(', ') : 'None'}
- Diet Type: ${userProfile.dietType}
- Daily Calorie Target: ${userProfile.tdee} calories

**Preferences:**
- Cuisine: ${preferences.cuisine?.join(', ') || 'Any'}
- Cooking Time: ${preferences.cookingTime || 'moderate'}
- Meals per day: ${preferences.mealCount || 3}

**Requirements:**
1. Ensure all meals meet the user's dietary restrictions and preferences
2. Provide exact nutritional information for each meal
3. Include detailed ingredients with precise measurements
4. Provide step-by-step cooking instructions
5. Include prep and cook times
6. Suggest appropriate difficulty level
7. Generate a comprehensive grocery list organized by category
8. Ensure the total daily calories match the target (${userProfile.tdee})

**Response Format:**
Return a JSON object with the following structure:
{
  "title": "Meal Plan Title",
  "description": "Brief description of the meal plan",
  "totalCalories": number,
  "totalProtein": number,
  "totalCarbs": number,
  "totalFat": number,
  "totalFiber": number,
  "totalSugar": number,
  "meals": [
    {
      "name": "Meal Name",
      "mealType": "BREAKFAST|LUNCH|DINNER|SNACK|PRE_WORKOUT|POST_WORKOUT",
      "calories": number,
      "protein": number,
      "carbs": number,
      "fat": number,
      "fiber": number,
      "sugar": number,
      "sodium": number,
      "ingredients": [
        {
          "name": "Ingredient Name",
          "amount": "1",
          "unit": "cup"
        }
      ],
      "instructions": ["Step 1", "Step 2"],
      "prepTime": number,
      "cookTime": number,
      "servings": number,
      "difficulty": "BEGINNER|INTERMEDIATE|ADVANCED",
      "tags": ["tag1", "tag2"]
    }
  ],
  "groceryList": [
    {
      "category": "Produce",
      "items": [
        {
          "name": "Item Name",
          "amount": "1",
          "unit": "lb"
        }
      ]
    }
  ]
}
    `;
  }

  private static buildWorkoutRecommendationPrompt(
    userProfile: UserProfile,
    availableWorkouts: any[],
    preferences: any
  ): string {
    return `
Recommend workout routines for the following user profile:

**User Profile:**
- Age: ${userProfile.age} years
- Gender: ${userProfile.gender}
- Goals: ${userProfile.goals.join(', ')}
- Activity Level: ${userProfile.activityLevel}

**Preferences:**
- Duration: ${preferences.duration || '30-45'} minutes
- Equipment: ${preferences.equipment?.join(', ') || 'Any'}
- Muscle Groups: ${preferences.muscleGroups?.join(', ') || 'Full body'}
- Difficulty: ${preferences.difficulty || 'Beginner to Intermediate'}

**Available Workouts:**
${availableWorkouts.map(workout => 
  `- ${workout.title} (${workout.duration}min, ${workout.difficulty}, ${workout.muscleGroups.join(', ')})`
).join('\n')}

**Requirements:**
1. Recommend 3-5 workout routines that match the user's goals and preferences
2. Include workout IDs from the available list
3. Provide a brief explanation for each recommendation
4. Consider progression and variety
5. Ensure workouts are appropriate for the user's fitness level

**Response Format:**
Return a JSON object with the following structure:
{
  "recommendations": [
    {
      "workoutId": "workout_id",
      "reason": "Why this workout is recommended",
      "priority": "high|medium|low",
      "suggestedSchedule": "When to do this workout"
    }
  ],
  "weeklyPlan": {
    "monday": ["workout_id_1"],
    "tuesday": ["workout_id_2"],
    "wednesday": ["workout_id_3"],
    "thursday": ["workout_id_4"],
    "friday": ["workout_id_5"],
    "saturday": ["workout_id_6"],
    "sunday": ["workout_id_7"]
  }
}
    `;
  }

  private static buildMealSwapPrompt(
    currentMeal: GeneratedMeal,
    userProfile: UserProfile,
    mealType: string,
    preferences: any
  ): string {
    return `
Generate a replacement meal for the following:

**Current Meal to Replace:**
- Name: ${currentMeal.name}
- Type: ${currentMeal.mealType}
- Calories: ${currentMeal.calories}
- Protein: ${currentMeal.protein}g
- Carbs: ${currentMeal.carbs}g
- Fat: ${currentMeal.fat}g

**User Profile:**
- Goals: ${userProfile.goals.join(', ')}
- Allergies: ${userProfile.allergies.length > 0 ? userProfile.allergies.join(', ') : 'None'}
- Diet Type: ${userProfile.dietType}

**Preferences:**
- Cuisine: ${preferences.cuisine?.join(', ') || 'Any'}
- Cooking Time: ${preferences.cookingTime || 'moderate'}
- Avoid: ${preferences.avoidIngredients?.join(', ') || 'None'}

**Requirements:**
1. Match the nutritional profile as closely as possible
2. Respect dietary restrictions and preferences
3. Provide detailed ingredients and instructions
4. Maintain similar prep/cook times
5. Ensure the meal is appropriate for the specified meal type

**Response Format:**
Return a JSON object with the same structure as the current meal.
    `;
  }

  private static validateAndFormatMealPlan(mealPlan: any): GeneratedMealPlan {
    // Add validation logic here
    return mealPlan as GeneratedMealPlan;
  }

  private static validateAndFormatMeal(meal: any): GeneratedMeal {
    // Add validation logic here
    return meal as GeneratedMeal;
  }
}