exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('workouts').del();
  
  // Inserts seed entries
  await knex('workouts').insert([
    {
      id: '550e8400-e29b-41d4-a716-446655440001',
      title: 'Morning Cardio Blast',
      description: 'Start your day with this energizing cardio workout that will get your heart pumping and blood flowing.',
      category: 'cardio',
      difficulty: 'beginner',
      duration_minutes: 20,
      calories_burned: 150,
      video_url: 'https://example.com/videos/morning-cardio-blast.mp4',
      thumbnail_url: 'https://example.com/thumbnails/morning-cardio.jpg',
      equipment_needed: JSON.stringify(['None']),
      muscle_groups: JSON.stringify(['Full Body', 'Cardiovascular']),
      tags: JSON.stringify(['morning', 'cardio', 'beginner', 'energy']),
      is_premium: false,
      is_featured: true,
      view_count: 1250,
      rating: 4.5,
      rating_count: 89
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440002',
      title: 'Upper Body Strength',
      description: 'Build strong arms, chest, and shoulders with this comprehensive upper body workout.',
      category: 'strength',
      difficulty: 'intermediate',
      duration_minutes: 45,
      calories_burned: 280,
      video_url: 'https://example.com/videos/upper-body-strength.mp4',
      thumbnail_url: 'https://example.com/thumbnails/upper-body.jpg',
      equipment_needed: JSON.stringify(['Dumbbells', 'Resistance Bands']),
      muscle_groups: JSON.stringify(['Chest', 'Shoulders', 'Arms', 'Back']),
      tags: JSON.stringify(['strength', 'upper body', 'dumbbells', 'muscle']),
      is_premium: true,
      is_featured: true,
      view_count: 2100,
      rating: 4.7,
      rating_count: 156
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440003',
      title: 'Yoga Flow for Flexibility',
      description: 'Improve your flexibility and reduce stress with this gentle yoga flow sequence.',
      category: 'yoga',
      difficulty: 'beginner',
      duration_minutes: 30,
      calories_burned: 120,
      video_url: 'https://example.com/videos/yoga-flow-flexibility.mp4',
      thumbnail_url: 'https://example.com/thumbnails/yoga-flow.jpg',
      equipment_needed: JSON.stringify(['Yoga Mat']),
      muscle_groups: JSON.stringify(['Full Body', 'Core', 'Back']),
      tags: JSON.stringify(['yoga', 'flexibility', 'stress relief', 'mindfulness']),
      is_premium: false,
      is_featured: true,
      view_count: 3200,
      rating: 4.8,
      rating_count: 234
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440004',
      title: 'HIIT Fat Burner',
      description: 'High-intensity interval training to maximize fat burning and boost metabolism.',
      category: 'hiit',
      difficulty: 'advanced',
      duration_minutes: 25,
      calories_burned: 350,
      video_url: 'https://example.com/videos/hiit-fat-burner.mp4',
      thumbnail_url: 'https://example.com/thumbnails/hiit-fat-burner.jpg',
      equipment_needed: JSON.stringify(['None']),
      muscle_groups: JSON.stringify(['Full Body', 'Cardiovascular', 'Core']),
      tags: JSON.stringify(['hiit', 'fat burning', 'high intensity', 'cardio']),
      is_premium: true,
      is_featured: true,
      view_count: 1800,
      rating: 4.6,
      rating_count: 98
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440005',
      title: 'Core Strengthening',
      description: 'Target your core muscles with this effective ab and back strengthening workout.',
      category: 'strength',
      difficulty: 'intermediate',
      duration_minutes: 20,
      calories_burned: 180,
      video_url: 'https://example.com/videos/core-strengthening.mp4',
      thumbnail_url: 'https://example.com/thumbnails/core-strengthening.jpg',
      equipment_needed: JSON.stringify(['Exercise Mat']),
      muscle_groups: JSON.stringify(['Core', 'Abs', 'Back']),
      tags: JSON.stringify(['core', 'abs', 'strength', 'stability']),
      is_premium: false,
      is_featured: false,
      view_count: 950,
      rating: 4.4,
      rating_count: 67
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440006',
      title: 'Pilates for Posture',
      description: 'Improve your posture and strengthen your deep core muscles with this Pilates session.',
      category: 'pilates',
      difficulty: 'beginner',
      duration_minutes: 35,
      calories_burned: 140,
      video_url: 'https://example.com/videos/pilates-posture.mp4',
      thumbnail_url: 'https://example.com/thumbnails/pilates-posture.jpg',
      equipment_needed: JSON.stringify(['Pilates Mat']),
      muscle_groups: JSON.stringify(['Core', 'Back', 'Posture']),
      tags: JSON.stringify(['pilates', 'posture', 'core', 'alignment']),
      is_premium: true,
      is_featured: false,
      view_count: 750,
      rating: 4.3,
      rating_count: 45
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440007',
      title: 'Dance Cardio Party',
      description: 'Have fun while burning calories with this energetic dance cardio workout.',
      category: 'dance',
      difficulty: 'beginner',
      duration_minutes: 30,
      calories_burned: 200,
      video_url: 'https://example.com/videos/dance-cardio-party.mp4',
      thumbnail_url: 'https://example.com/thumbnails/dance-cardio.jpg',
      equipment_needed: JSON.stringify(['None']),
      muscle_groups: JSON.stringify(['Full Body', 'Cardiovascular']),
      tags: JSON.stringify(['dance', 'cardio', 'fun', 'music']),
      is_premium: false,
      is_featured: true,
      view_count: 2800,
      rating: 4.7,
      rating_count: 189
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440008',
      title: 'Flexibility & Stretching',
      description: 'Improve your flexibility and reduce muscle tension with this comprehensive stretching routine.',
      category: 'flexibility',
      difficulty: 'beginner',
      duration_minutes: 25,
      calories_burned: 80,
      video_url: 'https://example.com/videos/flexibility-stretching.mp4',
      thumbnail_url: 'https://example.com/thumbnails/flexibility.jpg',
      equipment_needed: JSON.stringify(['Exercise Mat', 'Yoga Block']),
      muscle_groups: JSON.stringify(['Full Body', 'Flexibility']),
      tags: JSON.stringify(['flexibility', 'stretching', 'recovery', 'mobility']),
      is_premium: false,
      is_featured: false,
      view_count: 1200,
      rating: 4.5,
      rating_count: 78
    }
  ]);
};